// packages/create-rstack/template-lib-react-js/src/Button.jsx
import './button.css';

export const Button = ({ primary = false, size = 'medium', backgroundColor, label, ...props }) => {
  const mode = primary ? 'demo-button--primary' : 'demo-button--secondary';
  return (
    <button
      type="button"
      className={['demo-button', `demo-button--${size}`, mode].join(' ')}
      style={{ backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

// packages/create-rstack/template-lib-svelte-js/src/Button.svelte
<script>
  import './button.css';

  let {
    primary = false,
    backgroundColor,
    size = 'medium',
    label = 'Demo Button',
    onClick,
  } = $props();

  const mode = $derived(
    primary ? 'demo-button--primary' : 'demo-button--secondary',
  );
</script>

<button
  type="button"
  class={['demo-button', `demo-button--${size}`, mode].join(' ')}
  style:background-color={backgroundColor}
  onclick={onClick}
>
  {label}
</button>
