// packages/create-rstack/template-lib-svelte-ts/src/Button.svelte
<script lang="ts">
  import './button.css';

  type Size = 'small' | 'medium' | 'large';

  interface Props {
    primary?: boolean;
    backgroundColor?: string;
    size?: Size;
    label?: string;
    onClick?: () => void;
  }

  let {
    primary = false,
    backgroundColor,
    size = 'medium',
    label = 'Demo Button',
    onClick,
  }: Props = $props();

  const mode = $derived(
    primary ? 'demo-button--primary' : 'demo-button--secondary',
  );
</script>

<button
  type="button"
  class={['demo-button', `demo-button--${size}`, mode].join(' ')}
  style:background-color={backgroundColor}
  onclick={onClick}
>
  {label}
</button>

// packages/create-rstack/template-lib-vue-ts/src/Button.vue
<script setup lang="ts">
import { computed } from 'vue';
import './button.css';

interface Props {
  primary?: boolean;
  backgroundColor?: string;
  size?: 'small' | 'medium' | 'large';
  label: string;
  onClick?: () => void;
}

const {
  primary = false,
  backgroundColor = undefined,
  size = 'medium',
  label,
  onClick = undefined,
} = defineProps<Props>();

const mode = computed(() => (primary ? 'demo-button--primary' : 'demo-button--secondary'));
</script>

<template>
  <button
    type="button"
    :class="['demo-button', `demo-button--${size}`, mode]"
    :style="{ backgroundColor }"
    @click="onClick"
  >
    {{ label }}
  </button>
</template>
