// packages/create-rstack/template-app-vue/src/App.vue
<template>
  <div class="content">
    <h1>Rstack with Vue</h1>
    <p>Start building amazing things with Rstack.</p>
  </div>
</template>

<style scoped>
.content {
  display: flex;
  min-height: 100vh;
  line-height: 1.1;
  text-align: center;
  flex-direction: column;
  justify-content: center;
}

.content h1 {
  font-size: 3.6rem;
  font-weight: 700;
}

.content p {
  font-size: 1.2rem;
  font-weight: 400;
  opacity: 0.5;
}
</style>

// packages/create-rstack/template-app-svelte/src/App.svelte
<main>
  <div class="content">
    <h1>Rstack with Svelte</h1>
    <p>Start building amazing things with Rstack.</p>
  </div>
</main>

<style>
  .content {
    display: flex;
    min-height: 100vh;
    line-height: 1.1;
    text-align: center;
    flex-direction: column;
    justify-content: center;
  }

  .content h1 {
    font-size: 3.6rem;
    font-weight: 700;
  }

  .content p {
    font-size: 1.2rem;
    font-weight: 400;
    opacity: 0.5;
  }
</style>
