// packages/create-rstack/template-lib-react-js/src/Button.jsx
import './button.css';

export const Button = ({ primary = false, size = 'medium', backgroundColor, label, ...props }) => {
  const mode = primary ? 'demo-button--primary' : 'demo-button--secondary';
  return (
    <button
      type="button"
      className={['demo-button', `demo-button--${size}`, mode].join(' ')}
      style={{ backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

// packages/create-rstack/template-lib-vue-js/src/Button.vue
<script setup>
import { computed } from 'vue';
import './button.css';

const {
  primary = false,
  backgroundColor,
  size = 'medium',
  label,
  onClick,
} = defineProps({
  primary: {
    type: Boolean,
  },
  backgroundColor: {
    type: String,
  },
  size: {
    type: String,
  },
  label: {
    type: String,
  },
  onClick: {
    type: Function,
  },
});

const mode = computed(() =>
  primary ? 'demo-button--primary' : 'demo-button--secondary',
);
</script>

<template>
  <button
    type="button"
    :class="['demo-button', `demo-button--${size}`, mode]"
    :style="{ backgroundColor }"
    @click="onClick"
  >
    {{ label }}
  </button>
</template>
